### ISSUE TITLE
開発環境構築

### ISSUE THREAD

**Issue by konjikicity** [konjikicity/vowel-training#4]
部分的にSPAのページを作成するため、Rails6系＋ Vue.jsのプロジェクトを作成する。

**Comment by konjikicity** [comment]
部分的にSPAのアプリケーションを作成するため Rails6系+Vue.jsのプロジェクトを作成

**Comment by konjikicity** [comment]
## Rails newまでの手順
Rubyをrbenvにて管理 ver3.0.2を適用
```
rbenv local 3.0.2
```
rails newを実行以下のコードを実行した
```
rails _6.1.4.4_ new . --database=postgresql --webpack=vue --skip-test
```
rails7系がリリースされているがまだ間もないのでrails6系の最新verの安定版ver6.1.4.4を適用
デプロイ先はherokuを予定しているので公式にサポートされている`postgresql`をDBに適用
webpackでvueをインストール、rspecを使用する予定なのでminitest用ファイルはスキップする設定にした

**Comment by konjikicity** [comment]
0183520 で日本語化と時刻設定をした

`gem rails-i18n`,`gem enum_help`をGemfileに記述
apprication.rbにタイムゾーンの設定を追記

**Comment by konjikicity** [comment]
0414f64 各種デバッグの為のGemと設定、フォーマッターを導入
Vue用のESlintも導入した

**Comment by konjikicity** [comment]
e7b12e7 で開発に便利なGemを導入した
・foreman
・annotate
・seed_fu
seed_fuは/fixtures以下を読み込むのを失念していたため2c4f2e9 でフォルダを作成
環境ごとにseedファイルを分けて使えるようにした

## foremanのエラー
foremanで`bundle exec foreman start`コマンドでwebpackが立ち上がらないエラーが起きた
```
ERROR in ./app/javascript/packs/application.js
Module build failed (from ./node_modules/eslint-loader/dist/cjs.js):
TypeError: Cannot read property 'getFormatter' of undefined
    at getFormatter (/Users/onodaosamu/src/workspace/runteq/vowel-training/node_modules/eslint-loader/dist/getOptions.js:52:20)
    at getOptions (/Users/onodaosamu/src/workspace/runteq/vowel-training/node_modules/eslint-loader/dist/getOptions.js:30:23)
    at Object.loader (/Users/onodaosamu/src/workspace/runteq/vowel-training/node_modules/eslint-loader/dist/index.js:17:43)
```
eslintのバージョンに問題があることが発覚したので
`$ yarn remove eslint`, `$ yarn remove eslint-plugin-vue`を実行した後
`yarn add --dev eslint@^6.8.0 eslint-plugin-vue@^6.2.2`でバージョン指定をして実行して
インストールしなおしたら解決した。
